07 refactoring
Serg3/07_oop pull request #1
Opened 2021-06-03 14:33 UTC by Serg3

Part 7: ООП в Go (OOP in Go)

2021-06-05 14:15 UTC, DmitriyVTitov requested changes
Комментарии по исправлениям оставляйте в коде.
Попробуйте написать программу-клиент, посмотрите что получается.

2021-06-05 14:15 UTC, DmitriyVTitov commented on hw.go
> +	. "math"
Вот этого точно не надо! Я не знаю ни одного случая такого импорта по делу.

2021-06-05 14:15 UTC, DmitriyVTitov commented on hw.go
> +	x1, y1, x2, y2 float64
и как теперь этим пользоваться?
в другом пакете тип Geom будет доступен, а его поля - нет.

2021-06-07 13:12 UTC, DmitriyVTitov requested changes
Пока не принимаю.

2021-06-07 13:12 UTC, DmitriyVTitov commented on pkg/hw/hw.go
> +func (g Geom) Distance() float64 {
комментариев нет (для экспортируемых объектов)

2021-06-07 13:12 UTC, DmitriyVTitov commented on pkg/hw/hw.go
> +	if g.X1 < 0 || g.X2 < 0 || g.Y1 < 0 || g.Y2 < 0 {
Вот эти ограничения явно не являются частью вычислений расстояния.
Всегда разрабатывайте пакет так, как будто пользоваться им будет сторонний разработчик. Разве этот разработчик ждёт здесь таких ограничений?

2021-06-09 16:30 UTC, DmitriyVTitov approved these changes
Моё мнение не изменилось - ООП-подход тут явно лишний. Но дело ваше.

2021-06-09 16:30 UTC, DmitriyVTitov commented on pkg/hw/hw.go
> +package hw
что такое `hw`?

2021-06-09 20:58 UTC, Serg3 commented on pkg/hw/hw.go
> +package hw
Наверное, home work, только сейчас об этом задумался.

2021-06-09 21:08 UTC, DmitriyVTitov commented on pkg/hw/hw.go
> +package hw
Я та же подумал. Это как решение вопроса про неудачное имя пакета? :)

2021-06-09 21:15 UTC, Serg3 commented on pkg/hw/hw.go
> +package hw
Уже исправил, самому не понравилось :)

2021-06-12 11:05 UTC, merged